import { nodesToFormatted, countLines } from "../assets/code-view.js";

const WIDTH = 80;
const INDENT = 2;

const words = (s) => new Set(s.trim().split(/\s+/));

const RESERVED = words(`
  ADD AFTER ALL ALTER ANALYZE AND ANY ARRAY AS ASC AUTO_INCREMENT AUTOINCREMENT BEFORE BEGIN
  BETWEEN BY CALL CASCADE CASE CAST CHECK COLLATE COLUMN COMMIT CONCURRENTLY CONFLICT CONSTRAINT
  CREATE CROSS CUBE CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR DATABASE
  DECLARE DEFAULT DEFERRABLE DEFERRED DELETE DESC DESCRIBE DISTINCT DIV DO DROP DUPLICATE EACH ELSE
  ELSEIF ELSIF END ESCAPE EXCEPT EXCEPTION EXEC EXECUTE EXISTS EXIT EXPLAIN FALSE FETCH FILTER
  FOLLOWING FOR FOREIGN FROM FULL FUNCTION GLOB GRANT GROUP GROUPING HAVING IDENTITY IF ILIKE
  IMMEDIATE IN INDEX INITIALLY INNER INSERT INSTEAD INTERSECT INTERVAL INTO IS ISNULL ITERATE JOIN
  LATERAL LEAVE LEFT LIKE LIMIT LOCALTIME LOCALTIMESTAMP LOCK LOOP MATCHED MATERIALIZED MERGE
  MODIFY NATURAL NOT NOTHING NOTNULL NULL NULLS OF OFFSET ON ONLY OR ORDER OUTER OVER PARTITION
  PERFORM PIVOT PRAGMA PRECEDING PRIMARY PRINT PROCEDURE QUALIFY RAISE RAISERROR RECURSIVE
  REFERENCES REGEXP RELEASE RENAME REPEAT REPLACE RESTRICT RETURN RETURNING RETURNS REVOKE RIGHT
  RLIKE ROLLBACK ROLLUP ROWS COPY SAVEPOINT SCHEMA SELECT SEPARATOR SEQUENCE SESSION_USER SET SETS SHOW
  SIMILAR SOME TABLE TABLESAMPLE THEN TO TRANSACTION TRIGGER TRUE TRUNCATE UNBOUNDED UNION UNIQUE
  UNLOCK UNLOGGED UNPIVOT UNTIL UPDATE USE USING VACUUM VALUES VIEW WHEN WHERE WHILE WINDOW WITH
  WITHIN XOR
`);

// Only keywords inside DDL statements: elsewhere they are usually column names.
const DDL_SOFT = words(`
  ACTION ALWAYS ATTACH BTREE BRIN CACHE CHARACTER CHARSET CLUSTERED COMMENT CONNECT COST CYCLE
  DATA DEFINER DETACH DISABLE DOMAIN ENABLE ENGINE ENUM EXTENSION FULLTEXT GENERATED GIN GIST HASH
  IMMUTABLE INCLUDE INCREMENT INHERIT INVOKER KEY LANGUAGE LEAKPROOF LOGIN MAXVALUE MINVALUE NO
  NOLOGIN NONCLUSTERED NONE OPTION OWNED OWNER PARALLEL PASSWORD PERMISSIVE POLICY PRIVILEGES
  PUBLIC RESTRICTED RESTRICTIVE ROLE ROW ROW_FORMAT SAFE SECURITY SETOF SPATIAL STABLE START
  STATEMENT STORED STRICT SUPERUSER TABLESPACE TEMP TEMPORARY TYPE UNSAFE USAGE USER VALIDATE
  VIRTUAL VOLATILE
`);

const PHRASES = [
  "PRIMARY KEY", "FOREIGN KEY", "UNIQUE KEY", "NULLS FIRST", "NULLS LAST", "NO ACTION",
  "SET NULL", "SET DEFAULT", "ON DELETE", "ON UPDATE", "ON DUPLICATE KEY UPDATE", "DO NOTHING",
  "DO UPDATE", "IF NOT EXISTS", "IF EXISTS", "CURRENT ROW", "WITH TIME ZONE",
  "WITHOUT TIME ZONE", "AT TIME ZONE", "FETCH FIRST", "FETCH NEXT", "ROWS ONLY", "ROW ONLY",
  "WITH TIES", "FOR EACH ROW", "FOR EACH STATEMENT", "SKIP LOCKED", "NOWAIT", "FOR SHARE",
  "FOR NO KEY UPDATE", "FOR KEY SHARE", "START TRANSACTION", "ISOLATION LEVEL", "READ COMMITTED",
  "READ UNCOMMITTED", "REPEATABLE READ", "READ ONLY", "READ WRITE", "WITH ROLLUP",
  "WITH NO DATA", "WITH DATA", "WITH ORDINALITY", "INSERT IGNORE", "OR IGNORE", "CROSS APPLY",
  "OUTER APPLY", "LEFT SEMI", "LEFT ANTI", "SEMI JOIN", "ANTI JOIN", "WHEN MATCHED",
  "NOT MATCHED", "BY SOURCE", "BY TARGET", "CONNECT BY", "START WITH", "DEFAULT VALUES",
  "OWNER TO", "SET DATA TYPE", "ALTER COLUMN", "RESTART IDENTITY", "CONTINUE IDENTITY",
  "AS STRUCT", "AS VALUE", "SET NOCOUNT", "NOCOUNT ON", "NOCOUNT OFF", "BEGIN TRY", "END TRY",
  "BEGIN CATCH", "END CATCH", "END IF", "END LOOP", "END WHILE", "END REPEAT", "END CASE",
  "END FOR", "LOCK IN SHARE MODE", "SECURITY DEFINER", "SECURITY INVOKER", "NOT ATOMIC",
  "BEGIN ATOMIC", "EXIT WHEN", "CONTINUE WHEN", "GENERATED ALWAYS", "GENERATED BY DEFAULT",
  "STRAIGHT_JOIN", "DISTINCT ON",
].map((p) => p.split(" "));

const FUNCTIONS = words(`
  ABS ACOS ADD_MONTHS AGE ANY_VALUE APPROX_COUNT_DISTINCT ARRAY ARRAY_AGG ARRAY_APPEND ARRAY_CAT
  ARRAY_LENGTH ARRAY_POSITION ARRAY_REMOVE ARRAY_TO_STRING ASCII ASIN ATAN ATAN2 AVG BIT_LENGTH
  BOOL_AND BOOL_OR BTRIM CARDINALITY CAST CBRT CEIL CEILING CHAR_LENGTH CHARACTER_LENGTH CHARINDEX
  CHR COALESCE CONCAT CONCAT_WS CONVERT CORR COS COT COUNT COUNTIF COVAR_POP COVAR_SAMP CUME_DIST
  CURRENT_DATE CURRENT_SETTING CURRENT_TIMESTAMP CURRVAL DATE DATE_ADD DATE_DIFF DATE_FORMAT
  DATE_PART DATE_SUB DATE_TRUNC DATEADD DATEDIFF DATENAME DATEPART DATETIME DATETIME_DIFF DAY
  DAYOFWEEK DECODE DEGREES DENSE_RANK DIGEST ENCODE EOMONTH EVERY EXP EXTRACT FIRST_VALUE FLOOR
  FORMAT FORMAT_DATE FORMAT_TIMESTAMP FROM_UNIXTIME GEN_RANDOM_UUID GENERATE_ARRAY GENERATE_SERIES
  GETDATE GETUTCDATE GREATEST GROUP_CONCAT GROUPING HOUR IF IFNULL IIF INITCAP INSTR ISNULL
  JSON_AGG JSON_ARRAY JSON_ARRAY_LENGTH JSON_BUILD_ARRAY JSON_BUILD_OBJECT JSON_EACH
  JSON_EXTRACT JSON_EXTRACT_PATH JSON_EXTRACT_PATH_TEXT JSON_EXTRACT_SCALAR JSON_OBJECT
  JSON_OBJECT_AGG JSON_QUERY JSON_UNQUOTE JSON_VALUE JSONB_AGG JSONB_ARRAY_ELEMENTS
  JSONB_BUILD_ARRAY JSONB_BUILD_OBJECT JSONB_EACH JSONB_EXTRACT_PATH JSONB_EXTRACT_PATH_TEXT
  JSONB_OBJECT_AGG JSONB_SET LAG LAST_DAY LAST_INSERT_ID LAST_VALUE LCASE LEAD LEAST LEFT LEN
  LENGTH LISTAGG LN LOCATE LOG LOG10 LOG2 LOWER LPAD LTRIM MAKE_DATE MAKE_INTERVAL MAX MD5 MEDIAN
  MIN MINUTE MOD MONTH NEWID NEXTVAL NOW NTH_VALUE NTILE NULLIF NVL NVL2 OBJECT_ID OCTET_LENGTH
  PARSE_DATE PARSE_TIMESTAMP PERCENT_RANK PERCENTILE_CONT PERCENTILE_DISC PI POSITION POW POWER
  QUOTE_IDENT QUOTE_LITERAL QUOTE_NULLABLE RADIANS RAND RANDOM RANK REGEXP_CONTAINS
  REGEXP_EXTRACT REGEXP_LIKE REGEXP_MATCHES REGEXP_REPLACE REGEXP_SPLIT_TO_ARRAY
  REGEXP_SPLIT_TO_TABLE REGEXP_SUBSTR REPEAT REPLACE REVERSE RIGHT ROUND ROW ROW_NUMBER
  ROW_TO_JSON RPAD RTRIM SAFE_CAST SAFE_DIVIDE SCOPE_IDENTITY SECOND SETVAL SHA1 SHA256 SHA512
  SIGN SIN SPLIT SPLIT_PART SQRT STARTS_WITH STDDEV STDDEV_POP STDDEV_SAMP STR_TO_DATE STRFTIME
  STRING_AGG STRING_TO_ARRAY STRPOS STRUCT STUFF SUBSTR SUBSTRING SUM SYSDATE SYSDATETIME TAN
  TIMESTAMP TIMESTAMP_DIFF TIMESTAMP_TRUNC TIMESTAMPDIFF TO_CHAR TO_DATE TO_JSON TO_JSONB
  TO_NUMBER TO_TIMESTAMP TRANSLATE TRIM TRUNC TRY_CAST TRY_CONVERT UCASE UNIX_TIMESTAMP UNNEST
  UPPER UUID UUID_GENERATE_V4 VAR_POP VAR_SAMP VARIANCE WEEK YEAR
`);

const TYPES = words(`
  BIGINT BIGNUMERIC BIGSERIAL BLOB BOOL BOOLEAN BPCHAR BYTEA CHARACTER CIDR CLOB DATERANGE
  DATETIME DATETIME2 DATETIMEOFFSET DECIMAL DOUBLE FLOAT FLOAT4 FLOAT64 FLOAT8 GEOGRAPHY GEOMETRY
  HIERARCHYID HSTORE INET INT INT2 INT4 INT4RANGE INT64 INT8 INT8RANGE INTEGER JSONB LONGBLOB
  LONGTEXT MACADDR MEDIUMBLOB MEDIUMINT MEDIUMTEXT NCHAR NCLOB NTEXT NUMERIC NUMRANGE NVARCHAR
  NVARCHAR2 OID REAL REGCLASS ROWVERSION SERIAL SERIAL4 SERIAL8 SMALLDATETIME SMALLINT SMALLMONEY
  SMALLSERIAL SQL_VARIANT SYSNAME TIMESTAMPTZ TIMETZ TINYBLOB TINYINT TINYTEXT TSQUERY TSRANGE
  TSTZRANGE TSVECTOR UNIQUEIDENTIFIER VARBINARY VARBIT VARCHAR VARCHAR2
`);

// Type names that are also common column names: typed only in a type position.
const AMBIG_TYPES = words(`
  BINARY BIT BOX BYTES CHAR CIRCLE DATE IMAGE INTERVAL JSON LINE MONEY NUMBER OBJECT PATH POINT
  POLYGON RECORD STRING TEXT TIME TIMESTAMP UUID VARIANT XML YEAR
`);

const TYPE_CONT = words("PRECISION VARYING UNSIGNED SIGNED ZEROFILL");

const DATE_UNITS = words(`
  CENTURY DATE DAY DAYOFWEEK DAYOFYEAR DAYS DECADE DOW DOY EPOCH HOUR HOURS ISODOW ISOWEEK ISOYEAR
  MICROSECOND MICROSECONDS MILLENNIUM MILLISECOND MILLISECONDS MINUTE MINUTES MONTH MONTHS QUARTER
  SECOND SECONDS TIMEZONE WEEK WEEKS YEAR YEARS
`);

const UNIT_FNS = words(`
  DATE_ADD DATE_DIFF DATE_SUB DATE_TRUNC DATEADD DATEDIFF DATENAME DATEPART DATETIME_DIFF
  DATETIME_TRUNC EXTRACT TIMESTAMP_ADD TIMESTAMP_DIFF TIMESTAMP_SUB TIMESTAMP_TRUNC TIMESTAMPADD
  TIMESTAMPDIFF
`);

const KW_BEFORE_PAREN = words(`
  ALL AND ANY AS BETWEEN BY CASE CHECK CONFLICT CUBE DEFAULT DISTINCT ELSE EXCEPT EXCLUDE EXEC EXECUTE
  EXISTS FILTER FOR FROM HAVING IN INCLUDE INSERT INTERSECT INTO IS JOIN KEY LATERAL LIKE ILIKE LIMIT NOT
  OFFSET ON OR OVER PIVOT QUALIFY REFERENCES RETURN RETURNING ROLLUP SELECT SET SETS SOME TABLE
  TABLESAMPLE THEN UNION UNIQUE UNPIVOT USING VALUES WHEN WHERE WHILE WITH WITHIN
`);

const AS_FOLLOW = words(`
  BEGIN DECLARE DELETE ENUM EXEC EXECUTE IDENTITY IF INSERT MATERIALIZED MERGE NOT ON PERMISSIVE
  PRINT RANGE RESTRICTIVE RETURN SELECT SET STRUCT TABLE TRUNCATE UPDATE VALUE VALUES WHILE WITH
`);

const IDENT_AFTER = words(`
  COLUMN DATABASE DOMAIN EXTENSION FUNCTION INDEX INTO PROCEDURE REFERENCES ROLE SCHEMA SEQUENCE
  TABLE TO TRIGGER TYPE USER VIEW
`);

const TABLE_BEFORE_PAREN = words("INTO TABLE REFERENCES VIEW INDEX EXISTS ON TRIGGER JOIN FROM COPY");

const CONSTRAINT_STARTS = words(`
  CHECK CONSTRAINT EXCLUDE FOREIGN FULLTEXT INDEX KEY LIKE PERIOD PRIMARY SPATIAL UNIQUE
`);

const VALUE_END_KW = words(`
  CURRENT_DATE CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER END FALSE LOCALTIME LOCALTIMESTAMP NULL
  SESSION_USER TRUE
`);

const TXN_AFTER_BEGIN = words("TRANSACTION WORK TRAN DEFERRED IMMEDIATE EXCLUSIVE ISOLATION READ DISTRIBUTED");

const DML_START = words("SELECT WITH VALUES INSERT UPDATE DELETE MERGE UPSERT EXPLAIN");

const TSQL_STMT = words(`
  ALTER BEGIN BREAK CLOSE CONTINUE CREATE DEALLOCATE DECLARE DELETE DROP EXEC EXECUTE FETCH GOTO IF
  INSERT MERGE OPEN PRINT RAISERROR RETURN SELECT SET THROW TRUNCATE UPDATE WAITFOR WHILE WITH
`);

const END_FOLLOW = words("IF LOOP WHILE REPEAT FOR CASE TRY CATCH");

const MULTI_OPS = [
  "->>", "#>>", "<=>", "!~*", "~~*", "!~~", "-|-", "::", "->", "#>", "#-", "@>", "<@", "?|", "?&",
  "||", "&&", "<>", "!=", "<=", ">=", ":=", "=>", "<<", ">>", "~*", "!~", "~~", "**", "@@", "!!",
];

// ---------------------------------------------------------------------------
// Public API

export function viewSql(text) {
  const src = String(text ?? "").replace(/^﻿/, "");
  const lexer = new Lexer(src);
  const tokens = lexer.run();
  const stmts = splitStatements(tokens);
  const statements = stmts.filter((s) => !s.special && s.tokens.some((t) => t.type !== "comment")).length;
  let nodes;
  let truncated = lexer.truncated;
  try {
    const out = formatScript(stmts);
    nodes = out.nodes;
    truncated = truncated || out.truncated;
  } catch {
    nodes = verbatimNodes(src, tokens, stmts);
  }
  return { nodes, formatted: nodesToFormatted(nodes), truncated, statements };
}

export function formatSql(text) {
  return viewSql(text).formatted;
}

export function tokenizeSql(text) {
  const tokens = new Lexer(String(text ?? "")).run();
  for (const st of splitStatements(tokens)) {
    if (!st.special) classify(st.tokens, statementKind(st.tokens));
  }
  return tokens;
}

export function splitSql(text) {
  return splitStatements(new Lexer(String(text ?? "")).run())
    .filter((s) => !s.special && s.tokens.some((t) => t.type !== "comment"))
    .map((s) => s.tokens.map((t) => t.raw).join(" "));
}

// ---------------------------------------------------------------------------
// Lexer

const isWordStart = (c) => /[A-Za-z_À-￿]/.test(c);
const isWordCont = (c) => /[A-Za-z0-9_$À-￿]/.test(c);
const isDigit = (c) => c >= "0" && c <= "9";

class Lexer {
  constructor(text) {
    this.s = text;
    this.n = text.length;
    this.i = 0;
    this.tokens = [];
    this.truncated = false;
    this.delim = ";";
    this.nl = 0;
    this.bol = true;
    this.lineStart = 0;
    this.stmt = [];
  }

  run() {
    while (this.i < this.n) this.step();
    return this.tokens;
  }

  push(tok, start, end) {
    tok.start = start;
    tok.end = end;
    tok.raw = this.s.slice(start, end);
    tok.nl = this.nl;
    tok.col = start - this.lineStart;
    this.nl = 0;
    this.bol = false;
    this.i = end;
    this.tokens.push(tok);
    if (tok.type === "word") this.stmt.push(tok.upper);
    return tok;
  }

  endStatement() {
    const w = this.stmt;
    this.stmt = [];
    if (w[0] !== "COPY") return;
    const k = w.indexOf("STDIN");
    if (k > 0 && w[k - 1] === "FROM") this.readCopyData();
  }

  readCopyData() {
    let j = this.i;
    while (j < this.n && this.s[j] !== "\n") {
      if (!/\s/.test(this.s[j])) return;
      j += 1;
    }
    if (j >= this.n) return;
    const start = j + 1;
    let k = start;
    let end = this.n;
    let next = this.n;
    while (k < this.n) {
      let e = this.s.indexOf("\n", k);
      if (e < 0) e = this.n;
      if (this.s.slice(k, e).replace(/\r$/, "") === "\\.") {
        end = k;
        next = e;
        break;
      }
      k = e + 1;
    }
    this.nl += 1;
    this.lineStart = start;
    const value = this.s.slice(start, end).replace(/\r?\n$/, "");
    this.push({ type: "copydata", value, ended: next < this.n || end < this.n }, start, next);
  }

  step() {
    const s = this.s;
    const i = this.i;
    const c = s[i];
    if (c === "\n") {
      this.nl += 1;
      this.i += 1;
      this.bol = true;
      this.lineStart = this.i;
      return;
    }
    if (c === " " || c === "\t" || c === "\r" || c === "\f" || c === "\v" || c === " ") {
      this.i += 1;
      return;
    }
    if (this.bol && this.lineMeta()) return;

    if (this.delim !== ";" && s.startsWith(this.delim, i)) {
      this.push({ type: "delim", value: this.delim }, i, i + this.delim.length);
      this.endStatement();
      return;
    }

    const c2 = s[i + 1];
    if (c === "-" && c2 === "-") return this.lineComment(i);
    if (c === "#") {
      if (c2 === ">" || c2 === "-") return this.op(i);
      if (!this.bol && c2 && (isWordStart(c2) || c2 === "#")) return this.word(i, i + 1);
      return this.lineComment(i);
    }
    if (c === "/" && c2 === "*") return this.blockComment(i);
    if (c === "{" && (c2 === "{" || c2 === "%" || c2 === "#")) return this.template(i);
    if (c === "'") return this.quoted(i, i, "'", "");
    if (c === '"') return this.ident(i, '"', '"');
    if (c === "`") return this.ident(i, "`", "`");
    if (c === "[" && this.bracketIdent(i)) return this.ident(i, "[", "]");
    if (c === "$") return this.dollar(i);
    if (isDigit(c) || (c === "." && isDigit(c2) && !this.afterAtom())) return this.number(i);
    if (c === "?") {
      if (c2 === "|" || c2 === "&") return this.op(i);
      let j = i + 1;
      while (j < this.n && isDigit(s[j])) j += 1;
      this.push({ type: "param", value: s.slice(i, j) }, i, j);
      return;
    }
    if (c === ":" && c2 && isWordStart(c2) && s[i - 1] !== ":") {
      let j = i + 2;
      while (j < this.n && isWordCont(s[j])) j += 1;
      this.push({ type: "param", value: s.slice(i, j) }, i, j);
      return;
    }
    if (c === "@" && c2 && (isWordStart(c2) || c2 === "@")) {
      let j = i + 1;
      while (s[j] === "@") j += 1;
      while (j < this.n && isWordCont(s[j])) j += 1;
      this.push({ type: "param", value: s.slice(i, j) }, i, j);
      return;
    }
    if (c === "%") {
      const m = /^%(\([^)\s]*\))?[sdf](?![A-Za-z0-9_])/.exec(s.slice(i, i + 64));
      if (m) {
        this.push({ type: "param", value: m[0] }, i, i + m[0].length);
        return;
      }
    }
    if ("(),;.[]{}".includes(c)) {
      const tok = this.push({ type: "punct", value: c }, i, i + 1);
      if (c === ";" && this.delim === ";") {
        tok.term = true;
        this.endStatement();
      }
      return;
    }
    if (isWordStart(c)) return this.word(i, i);
    this.op(i);
  }

  lineMeta() {
    const s = this.s;
    let eol = s.indexOf("\n", this.i);
    if (eol < 0) eol = this.n;
    const line = s.slice(this.i, eol).replace(/\r$/, "");
    const d = /^delimiter\s+(\S+)\s*$/i.exec(line);
    if (d) {
      this.push({ type: "meta", value: line.trim(), delim: d[1] }, this.i, eol);
      this.delim = d[1];
      this.stmt = [];
      return true;
    }
    if (line[0] === "\\") {
      this.push({ type: "meta", value: line.trimEnd() }, this.i, eol);
      return true;
    }
    if (/^go(\s+\d+)?\s*(--.*)?$/i.test(line)) {
      this.push({ type: "go", value: line.trim() }, this.i, eol);
      this.stmt = [];
      return true;
    }
    return false;
  }

  lineComment(i) {
    let j = this.s.indexOf("\n", i);
    if (j < 0) j = this.n;
    const value = this.s.slice(i, j).replace(/\r$/, "").trimEnd();
    this.push({ type: "comment", value, line: true }, i, i + value.length || j);
  }

  blockComment(i) {
    const s = this.s;
    let depth = 1;
    let j = i + 2;
    while (j < this.n && depth) {
      if (s[j] === "/" && s[j + 1] === "*") {
        depth += 1;
        j += 2;
      } else if (s[j] === "*" && s[j + 1] === "/") {
        depth -= 1;
        j += 2;
      } else j += 1;
    }
    if (depth) this.truncated = true;
    const tok = { type: "comment", value: s.slice(i, j), block: true, closed: !depth };
    this.push(tok, i, j);
  }

  template(i) {
    const s = this.s;
    const close = { "{": "}}", "%": "%}", "#": "#}" }[s[i + 1]];
    let j = s.indexOf(close, i + 2);
    j = j < 0 ? this.n : j + 2;
    const value = s.slice(i, j);
    if (s[i + 1] === "{") this.push({ type: "tpl", value }, i, j);
    else this.push({ type: "comment", value, block: true, tpl: true, closed: true }, i, j);
  }

  quoted(start, i, q, prefix) {
    const s = this.s;
    let j = i + 1;
    let closed = false;
    while (j < this.n) {
      const c = s[j];
      if (c === q) {
        if (s[j + 1] === q) {
          j += 2;
          continue;
        }
        closed = true;
        break;
      }
      if (c === "\\" && q === "'") {
        j += 2;
        continue;
      }
      j += 1;
    }
    if (!closed) this.truncated = true;
    const value = s.slice(i + 1, Math.min(j, this.n));
    this.push({ type: "string", value, quote: q, prefix, closed }, start, closed ? j + 1 : this.n);
  }

  ident(i, open, close) {
    const s = this.s;
    let j = i + 1;
    let closed = false;
    while (j < this.n) {
      if (s[j] === close) {
        if (s[j + 1] === close && open !== "[") {
          j += 2;
          continue;
        }
        closed = true;
        break;
      }
      j += 1;
    }
    if (!closed) this.truncated = true;
    const end = closed ? j + 1 : this.n;
    this.push({ type: "qname", value: s.slice(i, end), closed }, i, end);
  }

  bracketIdent(i) {
    const prev = this.lastCode();
    if (prev) {
      if (prev.type === "qname" || prev.type === "string" || prev.type === "number") return false;
      if (prev.type === "punct" && (prev.value === ")" || prev.value === "]")) return false;
      if (prev.type === "word" && (!RESERVED.has(prev.upper) || prev.upper === "ARRAY")) return false;
    }
    return /^\[[A-Za-z_@#À-￿][^\]\n]*\]/.test(this.s.slice(i, i + 256));
  }

  afterAtom() {
    const prev = this.lastCode();
    if (!prev || prev.end !== this.i) return false;
    return prev.type === "word" || prev.type === "qname" || (prev.type === "punct" && prev.value === ")");
  }

  lastCode() {
    for (let k = this.tokens.length - 1; k >= 0; k -= 1) {
      if (this.tokens[k].type !== "comment") return this.tokens[k];
    }
    return null;
  }

  dollar(i) {
    const s = this.s;
    const m = /^\$([A-Za-z_À-￿][A-Za-z0-9_À-￿]*)?\$/.exec(s.slice(i, i + 128));
    if (m) {
      const tag = m[0];
      const close = s.indexOf(tag, i + tag.length);
      const closed = close >= 0;
      if (!closed) this.truncated = true;
      const end = closed ? close + tag.length : this.n;
      const value = s.slice(i + tag.length, closed ? close : this.n);
      this.push({ type: "string", value, quote: tag, prefix: "", closed, dollar: true }, i, end);
      return;
    }
    let j = i + 1;
    while (j < this.n && isWordCont(s[j])) j += 1;
    if (j > i + 1) this.push({ type: "param", value: s.slice(i, j) }, i, j);
    else this.op(i);
  }

  number(i) {
    const s = this.s;
    let j = i;
    const hex = /^0[xX][0-9a-fA-F_]+/.exec(s.slice(i, i + 64)) || /^0[bB][01_]+/.exec(s.slice(i, i + 130));
    if (hex) j = i + hex[0].length;
    else {
      while (j < this.n && (isDigit(s[j]) || s[j] === "_")) j += 1;
      if (s[j] === "." && s[j + 1] !== ".") {
        j += 1;
        while (j < this.n && (isDigit(s[j]) || s[j] === "_")) j += 1;
      }
      if ((s[j] === "e" || s[j] === "E") && (isDigit(s[j + 1]) || ((s[j + 1] === "+" || s[j + 1] === "-") && isDigit(s[j + 2])))) {
        j += 2;
        while (j < this.n && isDigit(s[j])) j += 1;
      }
    }
    if (j < this.n && isWordStart(s[j]) && !/[eE]/.test(s[j])) {
      // 1st, 2a: not a number, treat as a word.
      while (j < this.n && isWordCont(s[j])) j += 1;
      const value = s.slice(i, j);
      this.push({ type: "word", value, upper: value.toUpperCase() }, i, j);
      return;
    }
    this.push({ type: "number", value: s.slice(i, j) }, i, j);
  }

  word(start, i) {
    const s = this.s;
    let j = i + 1;
    while (j < this.n && isWordCont(s[j]) && !(this.delim !== ";" && s.startsWith(this.delim, j))) j += 1;
    const value = s.slice(start, j);
    if (s[j] === "'" && /^(e|n|x|b|r|rb|br|u|_[a-z0-9]+)$/i.test(value)) {
      this.quoted(start, j, "'", value);
      return;
    }
    if (s[j] === "&" && s[j + 1] === "'" && /^u$/i.test(value)) {
      this.quoted(start, j + 1, "'", `${value}&`);
      return;
    }
    this.push({ type: "word", value, upper: value.toUpperCase() }, start, j);
  }

  op(i) {
    const s = this.s;
    for (const o of MULTI_OPS) {
      if (s.startsWith(o, i)) {
        this.push({ type: "op", value: o }, i, i + o.length);
        return;
      }
    }
    this.push({ type: "op", value: s[i] }, i, i + 1);
  }
}

// ---------------------------------------------------------------------------
// Statements

function isTerm(t) {
  return t && (t.type === "delim" || (t.type === "punct" && t.value === ";"));
}

function isBlockBegin(toks, i) {
  const n = nextCode(toks, i);
  if (!n || isTerm(n) || n.type === "go") return false;
  if (n.type === "word" && TXN_AFTER_BEGIN.has(n.upper)) return false;
  return true;
}

function nextCode(toks, i) {
  for (let j = i + 1; j < toks.length; j += 1) {
    if (toks[j].type !== "comment") return toks[j];
  }
  return null;
}

function nextCodeIndex(toks, i) {
  for (let j = i + 1; j < toks.length; j += 1) {
    if (toks[j].type !== "comment") return j;
  }
  return -1;
}

function splitStatements(tokens) {
  const out = [];
  let cur = [];
  let stack = [];
  let skipCase = -1;
  const flush = (term) => {
    if (cur.length || term) out.push({ tokens: cur, term, trail: [] });
    cur = [];
    stack = [];
  };
  for (let i = 0; i < tokens.length; i += 1) {
    const t = tokens[i];
    if (t.type === "meta" || t.type === "go" || t.type === "copydata") {
      flush(null);
      out.push({ special: t, tokens: [t], trail: [] });
      continue;
    }
    if (t.type === "delim" || (t.type === "punct" && t.value === ";" && t.term && !stack.includes("begin"))) {
      flush(t);
      continue;
    }
    if (t.type === "word") {
      if (t.upper === "BEGIN" && isBlockBegin(tokens, i)) stack.push("begin");
      else if (t.upper === "CASE") {
        if (skipCase === i) skipCase = -1;
        else stack.push("case");
      } else if (t.upper === "END" && stack.length) {
        const j = nextCodeIndex(tokens, i);
        const nx = j >= 0 && tokens[j].type === "word" && tokens[j].nl === 0 ? tokens[j].upper : "";
        if (!["IF", "LOOP", "WHILE", "REPEAT", "FOR"].includes(nx)) {
          stack.pop();
          if (nx === "CASE") skipCase = j;
        }
      }
    }
    cur.push(t);
  }
  flush(null);

  // A comment on the same line as `;` belongs to the statement it ends.
  for (let k = 1; k < out.length; k += 1) {
    const prev = out[k - 1];
    const st = out[k];
    if (prev.special || st.special || !prev.term) continue;
    while (st.tokens.length && st.tokens[0].type === "comment" && st.tokens[0].nl === 0) {
      prev.trail.push(st.tokens.shift());
    }
  }
  for (const st of out) st.nl = st.tokens[0]?.nl ?? st.term?.nl ?? 0;
  return out.filter((st) => st.special || st.tokens.length || st.trail.length || st.term?.type === "delim");
}

function statementKind(toks) {
  const code = toks.filter((t) => t.type !== "comment");
  const first = code[0];
  if (!first) return "dml";
  if (first.type === "punct" && first.value === "(") return "dml";
  if (first.type !== "word") return "other";
  const up = first.upper;
  if (DML_START.has(up)) return "dml";
  if (up === "REPLACE" && code[1]?.upper === "INTO") return "dml";
  if (up === "DECLARE") return "declare";
  if (["CREATE", "ALTER", "DROP", "COMMENT", "GRANT", "REVOKE", "TRUNCATE", "DO", "RENAME"].includes(up)) return "ddl";
  return "other";
}

// ---------------------------------------------------------------------------
// Classification

function classify(toks, kind) {
  const code = toks.filter((t) => t.type !== "comment");
  const encl = new Array(code.length).fill(-1);
  const match = new Array(code.length).fill(-1);
  const stack = [];
  for (let i = 0; i < code.length; i += 1) {
    const t = code[i];
    t.role = null;
    t.k = null;
    t.v = undefined;
    t.cls = undefined;
    t.unary = false;
    t.body = false;
    t.forceBreak = false;
    encl[i] = stack.length ? stack[stack.length - 1] : -1;
    if (t.type === "punct" && (t.value === "(" || t.value === "[")) stack.push(i);
    else if (t.type === "punct" && (t.value === ")" || t.value === "]") && stack.length) match[stack.pop()] = i;
  }
  const ctx = { code, encl, match, kind };
  markDefs(ctx);
  markPhrases(code);
  for (let i = 0; i < code.length; i += 1) {
    const t = code[i];
    if (t.type === "word") classifyWord(ctx, i);
    else if (t.type === "number") t.cls = "n";
    else if (t.type === "param" || t.type === "tpl") t.cls = "param";
    else if (t.type === "punct") t.cls = "p";
    else if (t.type === "op") {
      t.cls = "p";
      if (t.value === "-" || t.value === "+" || t.value === "~") {
        const prev = code[i - 1];
        t.unary =
          !prev ||
          prev.type === "op" ||
          (prev.type === "punct" && prev.value !== ")" && prev.value !== "]") ||
          (prev.type === "word" && prev.k === "kw" && !VALUE_END_KW.has(prev.upper));
      }
    }
  }
  markBodies(ctx);
}

function setKind(t, k) {
  t.k = k;
  if (k === "kw") {
    t.v = t.upper;
    t.cls = t.upper === "TRUE" || t.upper === "FALSE" ? "b" : t.upper === "NULL" ? "u" : "kw";
  } else if (k === "fn") {
    t.v = FUNCTIONS.has(t.upper) ? t.upper : t.value;
    t.cls = "fn";
  } else if (k === "type") {
    t.v = TYPES.has(t.upper) || AMBIG_TYPES.has(t.upper) || TYPE_CONT.has(t.upper) ? t.upper : t.value;
    t.cls = "ty";
  } else {
    t.v = t.value;
    t.cls = undefined;
  }
}

function isP(t, v) {
  return t && t.type === "punct" && t.value === v;
}

function isW(t, up) {
  return t && t.type === "word" && (up == null || t.upper === up);
}

function markPhrases(code) {
  for (let i = 0; i < code.length; i += 1) {
    if (!isW(code[i]) || code[i].role || isP(code[i - 1], ".")) continue;
    for (const ph of PHRASES) {
      let ok = true;
      for (let k = 0; k < ph.length; k += 1) {
        const t = code[i + k];
        if (!isW(t, ph[k]) || t.role || isP(code[i + k + 1], ".") || isP(code[i + k + 1], "(")) {
          ok = false;
          break;
        }
      }
      if (!ok) continue;
      for (let k = 0; k < ph.length; k += 1) code[i + k].role = "kw";
      i += ph.length - 1;
      break;
    }
  }
}

function markDefs(ctx) {
  const { code, match, kind } = ctx;
  const ups = code.map((t) => (t.type === "word" ? t.upper : ""));
  const first = ups[0];
  if (kind === "declare") {
    markDefItems(ctx, 1, code.length, true);
    return;
  }
  if (kind === "decl") {
    markDefItem(ctx, 0, code.length);
    return;
  }
  if (first === "CREATE") {
    const tableAt = ups.indexOf("TABLE");
    const fnAt = ups.findIndex((u) => u === "FUNCTION" || u === "PROCEDURE");
    const asAt = ups.indexOf("AS");
    if (tableAt > 0 && (fnAt < 0 || tableAt < fnAt)) {
      const open = code.findIndex((t, k) => k > tableAt && isP(t, "("));
      if (open > 0 && (asAt < 0 || open < asAt) && match[open] > 0) {
        code[open].forceBreak = true;
        markDefItems(ctx, open + 1, match[open], false);
      }
    } else if (fnAt > 0) {
      const open = code.findIndex((t, k) => k > fnAt && isP(t, "("));
      if (open > 0 && match[open] > 0) markDefItems(ctx, open + 1, match[open], false);
      const ret = ups.indexOf("RETURNS");
      if (ret > 0) {
        if (ups[ret + 1] === "TABLE" && isP(code[ret + 2], "(") && match[ret + 2] > 0) {
          markDefItems(ctx, ret + 3, match[ret + 2], false);
        } else if (ups[ret + 1] === "SETOF") markType(code, ret + 2);
        else markType(code, ret + 1);
      }
    }
  }
  if (first === "ALTER") {
    for (let i = 1; i < code.length; i += 1) {
      if (ups[i] === "ADD" && encl(ctx, i) < 0) {
        let j = i + 1;
        if (ups[j] === "COLUMN") j += 1;
        else if (CONSTRAINT_STARTS.has(ups[j]) || ups[j] === "PARTITION") continue;
        if (ups[j] === "IF" && ups[j + 1] === "NOT" && ups[j + 2] === "EXISTS") j += 3;
        markDefItem(ctx, j, code.length);
      }
      if (ups[i] === "TYPE" && (ups[i - 1] === "DATA" || code[i - 1]?.type === "word" || code[i - 1]?.type === "qname")) {
        if (ups[i - 2] === "ALTER" || ups[i - 2] === "COLUMN" || ups[i - 1] === "DATA") markType(code, i + 1);
      }
    }
  }
}

function encl(ctx, i) {
  return ctx.encl[i];
}

function markType(code, j) {
  const t = code[j];
  if (!t || t.type !== "word" && t.type !== "qname") return j;
  t.role = "type";
  j += 1;
  while (code[j] && isW(code[j]) && TYPE_CONT.has(code[j].upper)) {
    code[j].role = "type";
    j += 1;
  }
  return j;
}

function markDefItems(ctx, from, to, declare) {
  const { code, encl: en } = ctx;
  const base = en[from] ?? -1;
  let start = from;
  for (let i = from; i <= to; i += 1) {
    if (i === to || (isP(code[i], ",") && en[i] === base)) {
      markDefItem(ctx, start, i, declare);
      start = i + 1;
    }
  }
}

function markDefItem(ctx, from, to) {
  const { code } = ctx;
  let j = from;
  while (j < to && isW(code[j]) && ["IN", "OUT", "INOUT", "VARIADIC"].includes(code[j].upper)) {
    code[j].role = "kw";
    j += 1;
  }
  const first = code[j];
  if (!first || j >= to) return;
  if (isW(first) && CONSTRAINT_STARTS.has(first.upper)) return;
  const after = code[j + 1];
  if (isW(first) && (TYPES.has(first.upper) || AMBIG_TYPES.has(first.upper)) && (j + 1 >= to || isP(after, "(") || isP(after, "["))) {
    markType(code, j);
    return;
  }
  if (first.type !== "word" && first.type !== "qname" && first.type !== "param") return;
  if (first.type === "word") first.role = "ident";
  if (j + 1 < to && isW(code[j + 1]) && code[j + 1].upper === "CONSTANT") {
    code[j + 1].role = "kw";
    j += 1;
  }
  if (j + 1 < to && isW(code[j + 1], "AS")) j += 1;
  if (j + 1 < to) markType(code, j + 1);
}

function markBodies(ctx) {
  const { code } = ctx;
  let lang = "";
  for (let i = 0; i < code.length - 1; i += 1) {
    if (isW(code[i], "LANGUAGE") && code[i].k === "kw") {
      const n = code[i + 1];
      lang = String(n.type === "string" ? n.value : n.value).toLowerCase().replace(/["'`]/g, "");
    }
  }
  for (let i = 1; i < code.length; i += 1) {
    const t = code[i];
    const prev = code[i - 1];
    if (t.type === "string" && t.dollar && isW(prev) && (prev.upper === "AS" || prev.upper === "DO")) {
      t.body = true;
      t.lang = lang || "plpgsql";
    }
  }
}

function classifyWord(ctx, i) {
  const { code, kind } = ctx;
  const t = code[i];
  const up = t.upper;
  const prev = code[i - 1];
  const next = code[i + 1];
  if (t.role) return setKind(t, t.role);
  if (isP(prev, ".") && !isP(next, "(")) return setKind(t, "ident");
  if (isP(next, ".")) return setKind(t, "ident");
  if (prev && prev.type === "op" && prev.value === "::") return setKind(t, "type");
  if (i === 0 && (up === "IF" || up === "WHILE")) return setKind(t, "kw");

  if (DATE_UNITS.has(up) && isUnit(ctx, i)) return setKind(t, "kw");

  if (isP(next, "(")) {
    if (KW_BEFORE_PAREN.has(up)) return setKind(t, "kw");
    if (TYPES.has(up) && !FUNCTIONS.has(up)) return setKind(t, "type");
    if (AMBIG_TYPES.has(up) && !FUNCTIONS.has(up) && typeContext(ctx, i)) return setKind(t, "type");
    if (FUNCTIONS.has(up)) return setKind(t, "fn");
    let head = i;
    while (head > 1 && isP(code[head - 1], ".")) head -= 2;
    const before = code[head - 1];
    if (isW(before) && TABLE_BEFORE_PAREN.has(before.upper) && before.k === "kw") return setKind(t, "ident");
    if (kind === "ddl" && isW(before, "USING")) return setKind(t, "ident");
    if (head !== i) return setKind(t, "fn");
    const close = ctx.match[i + 1];
    if (close > 0 && isW(code[close + 1], "AS")) return setKind(t, "ident");
    return setKind(t, "fn");
  }

  if (isW(prev, "AS") && prev.k === "kw") {
    if (AS_FOLLOW.has(up)) return setKind(t, "kw");
    if (inCast(ctx, i) || TYPES.has(up)) return setKind(t, "type");
    return setKind(t, "ident");
  }

  if (RESERVED.has(up)) return setKind(t, "kw");
  if ((up === "TOP" && isW(prev) && ["SELECT", "DISTINCT", "ALL", "DELETE", "UPDATE"].includes(prev.upper)) ||
      (up === "PERCENT" && isW(code[i - 2], "TOP"))) {
    return setKind(t, "kw");
  }
  if (kind === "ddl" && DDL_SOFT.has(up) && !identPosition(code, i)) return setKind(t, "kw");
  if (TYPES.has(up)) return setKind(t, "type");
  if (AMBIG_TYPES.has(up) && typeContext(ctx, i)) return setKind(t, "type");
  if (TYPE_CONT.has(up) && prev && prev.k === "type") return setKind(t, "type");
  return setKind(t, "ident");
}

function identPosition(code, i) {
  const prev = code[i - 1];
  if (!prev) return false;
  if (isP(prev, ",") || isP(prev, "(")) return true;
  return isW(prev) && (IDENT_AFTER.has(prev.upper) || prev.upper === "EXISTS") && prev.k === "kw";
}

function inCast(ctx, i) {
  const open = ctx.encl[i];
  if (open < 1) return false;
  const fn = ctx.code[open - 1];
  return isW(fn) && ["CAST", "TRY_CAST", "SAFE_CAST", "CONVERT", "TRY_CONVERT"].includes(fn.upper);
}

function typeContext(ctx, i) {
  const { code } = ctx;
  const prev = code[i - 1];
  const next = code[i + 1];
  if (isW(prev) && (prev.upper === "RETURNS" || prev.upper === "TYPE")) return true;
  if (next && next.type === "string" && !next.prefix && ["DATE", "TIME", "TIMESTAMP", "INTERVAL", "JSON"].includes(code[i].upper)) return true;
  return false;
}

function isUnit(ctx, i) {
  const { code } = ctx;
  const prev = code[i - 1];
  const next = code[i + 1];
  if (prev && (prev.type === "number" || prev.type === "string") && isW(code[i - 2], "INTERVAL")) return true;
  if (isW(prev, "TO") && isW(code[i - 3], "INTERVAL")) return true;
  const open = ctx.encl[i];
  if (open < 1) return false;
  const fn = code[open - 1];
  if (!isW(fn) || !UNIT_FNS.has(fn.upper)) return false;
  if (fn.upper === "EXTRACT") return isW(next, "FROM");
  const startArg = isP(prev, "(") || isP(prev, ",");
  const endArg = isP(next, ")") || isP(next, ",");
  return startArg && endArg;
}

// ---------------------------------------------------------------------------
// Tree

function nest(toks) {
  const root = { items: [] };
  const stack = [root];
  for (const t of toks) {
    const top = stack[stack.length - 1];
    if (t.type === "punct" && (t.value === "(" || t.value === "[")) {
      const g = { kind: "group", open: t, close: null, items: [], forceBreak: Boolean(t.forceBreak) };
      top.items.push(g);
      stack.push(g);
      continue;
    }
    if (t.type === "punct" && (t.value === ")" || t.value === "]")) {
      let k = stack.length - 1;
      while (k > 0 && stack[k].kind === "case") k -= 1;
      if (k > 0) {
        stack[k].close = t;
        stack.length = k;
        continue;
      }
      top.items.push(t);
      continue;
    }
    if (t.type === "word" && t.k === "kw" && t.upper === "CASE") {
      const c = { kind: "case", open: t, close: null, items: [] };
      top.items.push(c);
      stack.push(c);
      continue;
    }
    if (t.type === "word" && t.k === "kw" && t.upper === "END" && top.kind === "case") {
      top.close = t;
      stack.pop();
      continue;
    }
    top.items.push(t);
  }
  return root.items;
}

const isGroup = (it) => it && it.kind === "group";
const isCase = (it) => it && it.kind === "case";
const isComment = (it) => it && !it.kind && it.type === "comment";
const isKw = (it, up) => it && !it.kind && it.type === "word" && it.k === "kw" && (up == null || it.upper === up);
const isLineComment = (t) => t.type === "comment" && (t.line || (t.block && t.value.includes("\n")));

function firstCode(items) {
  return items.find((it) => !isComment(it));
}

function isQuery(items) {
  const f = firstCode(items);
  if (!f) return false;
  if (isGroup(f)) return isQuery(f.items);
  return isKw(f) && ["SELECT", "WITH", "VALUES", "INSERT", "UPDATE", "DELETE", "MERGE", "TABLE"].includes(f.upper) &&
    (f.upper !== "TABLE" || items.length === 2);
}

function isWindowSpec(items) {
  const f = firstCode(items);
  const n = items[items.indexOf(f) + 1];
  return isKw(f) && (((f.upper === "PARTITION" || f.upper === "ORDER") && isKw(n, "BY")) || ["ROWS", "RANGE", "GROUPS"].includes(f.upper));
}

// ---------------------------------------------------------------------------
// Output

function outTok(t) {
  if (t.type === "word") {
    return { type: t.k === "kw" ? "keyword" : t.k === "fn" ? "defname" : "name", value: t.v ?? t.value, cls: t.cls };
  }
  if (t.type === "string") {
    return { type: "string", value: t.value, quote: t.quote, prefix: t.prefix, side: t.closed === false ? "open" : undefined };
  }
  if (t.type === "comment") return { type: "comment", value: t.value, cls: t.tpl ? "param" : "c" };
  return { type: t.type, value: t.value, cls: t.cls };
}

function tokLen(t) {
  if (t.type === "string") {
    if (t.value.includes("\n")) return Infinity;
    return (t.prefix || "").length + t.quote.length * 2 + t.value.length;
  }
  if (t.type === "comment" && isLineComment(t)) return Infinity;
  return String(t.v ?? t.value).length;
}

function spaceBetween(a, b) {
  if (!a) return false;
  if (b.type === "comment" || a.type === "comment") return true;
  const av = a.type === "punct" || a.type === "op" ? a.value : null;
  const bv = b.type === "punct" || b.type === "op" ? b.value : null;
  if (bv === "," || bv === ";" || bv === ")" || bv === "]" || bv === ".") return false;
  if (av === "(" || av === "[" || av === ".") return false;
  if (av === "::" || bv === "::" || av === ":" || bv === ":") return false;
  if (b.type === "delim") return false;
  if (a.type === "op" && a.unary) return false;
  if (bv === "(") {
    if (a.type === "word") return a.k === "kw" || a.k === "ident";
    if (a.type === "param" || a.type === "tpl") return false;
    return av !== "(";
  }
  if (bv === "[") {
    if (a.type === "word" || a.type === "qname" || av === ")" || av === "]" || a.type === "param") return false;
  }
  return true;
}

class Out {
  constructor() {
    this.root = [];
    this.stack = [this.root];
    this.cur = null;
    this.prev = null;
    this.col = 0;
    this.lineIndent = 0;
    this.needBreak = false;
    this.truncated = false;
  }

  get top() {
    return this.stack[this.stack.length - 1];
  }

  newLine(indent) {
    const line = { type: "line", tokens: indent ? [{ type: "space", value: " ".repeat(indent) }] : [] };
    line.parent = this.top;
    this.top.push(line);
    this.cur = line;
    this.prev = null;
    this.col = indent;
    this.lineIndent = indent;
    this.needBreak = false;
    return line;
  }

  blank() {
    this.top.push({ type: "line", tokens: [] });
    this.cur = null;
  }

  hasContent() {
    return Boolean(this.cur && this.prev);
  }

  ensure() {
    if (!this.cur) this.newLine(0);
    else if (this.needBreak) this.newLine(this.lineIndent);
  }

  add(tok, len) {
    this.cur.tokens.push(tok);
    this.col += len;
  }

  push(t) {
    this.ensure();
    if (spaceBetween(this.prev, t)) this.add({ type: "space", value: " " }, 1);
    if (t.type === "string" && t.value.includes("\n")) this.pushMultiString(t);
    else this.add(outTok(t), tokLen(t));
    this.prev = t;
  }

  pushMultiString(t) {
    const parts = t.value.split("\n");
    const indent = this.lineIndent;
    const last = parts.length - 1;
    this.add({ type: "string", value: parts[0], quote: t.quote, prefix: t.prefix, side: "open" }, 0);
    for (let k = 1; k <= last; k += 1) {
      const line = { type: "line", tokens: [], parent: this.top };
      this.top.push(line);
      this.cur = line;
      this.col = 0;
      const closing = k === last && t.closed !== false;
      line.tokens.push({ type: "string", value: parts[k], quote: closing ? t.quote : "", side: closing ? "close" : undefined });
      this.col = parts[k].length + (closing ? t.quote.length : 0);
    }
    this.lineIndent = indent;
  }

  pushComment(c) {
    if (c.nl > 0 && this.hasContent()) this.newLine(this.lineIndent);
    else this.ensure();
    if (this.prev) this.add({ type: "space", value: " " }, 1);
    if (c.block && c.value.includes("\n")) {
      const startCol = this.col;
      const lines = c.value.split("\n");
      this.add({ type: "comment", value: lines[0], cls: c.tpl ? "param" : "c" }, lines[0].length);
      for (let k = 1; k < lines.length; k += 1) {
        const lead = /^[ \t]*/.exec(lines[k])[0].length;
        const text = lines[k].slice(Math.min(lead, c.col));
        const line = { type: "line", tokens: [], parent: this.top };
        this.top.push(line);
        this.cur = line;
        if (startCol) line.tokens.push({ type: "space", value: " ".repeat(startCol) });
        line.tokens.push({ type: "comment", value: text, cls: c.tpl ? "param" : "c" });
        this.col = startCol + text.length;
      }
    } else {
      this.add(outTok(c), c.value.length);
    }
    this.prev = c;
    if (c.line || c.nl > 0) this.needBreak = true;
  }

  // `;` or `,` goes before a trailing line comment, never after it.
  pushPunct(t) {
    const toks = this.cur?.tokens;
    if (this.needBreak && toks) {
      let k = toks.length;
      while (k > 0 && (toks[k - 1].type === "comment" || toks[k - 1].type === "space")) k -= 1;
      const hasCode = toks.slice(0, k).some((x) => x.type !== "space");
      if (hasCode) {
        while (k < toks.length && toks[k].type === "space") k += 1;
        toks.splice(k, 0, outTok(t), { type: "space", value: " " });
        while (toks[k - 1]?.type === "space" && k - 1 > 0 && toks[k - 2]?.type !== "space") {
          toks.splice(k - 1, 1);
          break;
        }
        return;
      }
    }
    this.ensure();
    this.add(outTok(t), String(t.value).length);
    this.prev = t;
  }

  openBlock() {
    const line = this.cur;
    if (line.block) {
      this.stack.push(line.block.children);
      return;
    }
    const container = line.parent;
    const idx = container.lastIndexOf(line);
    const block = { type: "block", header: line.tokens, children: [] };
    container[idx] = block;
    line.block = block;
    this.stack.push(block.children);
  }

  closeBlock() {
    this.stack.pop();
  }

  appendNodes(nodes) {
    for (const n of nodes) {
      if (n.type === "line") n.parent = this.top;
      this.top.push(n);
    }
    this.cur = null;
  }
}

function flatten(nodes) {
  const out = [];
  for (const n of nodes) {
    if (n.type !== "block") {
      out.push({ type: "line", tokens: n.tokens });
      continue;
    }
    const children = flatten(n.children);
    if (countLines(children) < 2) {
      out.push({ type: "line", tokens: n.header }, ...children);
    } else {
      out.push({ type: "block", header: n.header, children });
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Widths

function itemWidth(it) {
  if (it.kind) {
    if (it._w != null) return it._w;
    let w = tokLen(it.open) + seqWidth(it.items, it.open);
    if (it.close) {
      const last = lastTok(it.items) || it.open;
      w += (spaceBetween(last, it.close) ? 1 : 0) + tokLen(it.close);
    }
    it._w = w;
    return w;
  }
  return tokLen(it);
}

function firstTok(it) {
  return it.kind ? it.open : it;
}

function lastTok(items) {
  const it = items[items.length - 1];
  if (!it) return null;
  if (it.kind) return it.close || lastTok(it.items) || it.open;
  return it;
}

function seqWidth(items, prev = null) {
  let w = 0;
  for (const it of items) {
    if (prev && spaceBetween(prev, firstTok(it))) w += 1;
    w += itemWidth(it);
    if (w === Infinity) return w;
    prev = it.kind ? it.close || lastTok(it.items) || it.open : it;
  }
  return w;
}

function hasLineComment(it) {
  if (!it.kind) return isLineComment(it) || (it.type === "string" && it.value.includes("\n"));
  if (it._lc == null) it._lc = it.items.some(hasLineComment);
  return it._lc;
}

function hasBody(it) {
  if (!it.kind) return it.type === "string" && it.body;
  return it.items.some(hasBody);
}

// ---------------------------------------------------------------------------
// Script

function formatScript(stmts) {
  const out = new Out();
  let prevMulti = null;
  let count = 0;
  for (const st of stmts) {
    const sub = new Out();
    formatTop(sub, st);
    if (sub.truncated) out.truncated = true;
    const lines = countLines(sub.root);
    if (!lines) continue;
    if (prevMulti !== null) {
      const special = st.special?.type;
      const want = special === "copydata" ? false : prevMulti || lines > 1 || st.nl >= 2;
      if (want) out.root.push({ type: "line", tokens: [] });
    }
    out.root.push(...sub.root);
    prevMulti = lines > 1 && st.special?.type !== "copydata";
    count += 1;
  }
  return { nodes: flatten(out.root), truncated: out.truncated, count };
}

function formatTop(out, st) {
  if (st.special) return formatSpecial(out, st.special);
  const toks = st.tokens.slice();
  let firstOut = true;
  while (toks.length && toks[0].type === "comment") {
    const c = toks.shift();
    if (!firstOut && c.nl >= 2) out.blank();
    out.newLine(0);
    out.pushComment(c);
    firstOut = false;
  }
  const trail = [];
  while (toks.length && toks[toks.length - 1].type === "comment") trail.unshift(toks.pop());
  if (toks.length) {
    if (!firstOut && toks[0].nl >= 2) out.blank();
    emitStatement(out, toks, 0, {});
  }
  if (st.term) {
    if (!out.cur) out.newLine(0);
    out.pushPunct(st.term.type === "delim" ? { type: "delim", value: st.term.value, cls: "p" } : { type: "punct", value: ";", cls: "p" });
  }
  for (const c of [...trail, ...st.trail]) out.pushComment(c);
}

function formatSpecial(out, t) {
  if (t.type === "copydata") {
    for (const line of t.value.split("\n")) {
      out.newLine(0);
      out.cur.tokens.push({ type: "text", value: line.replace(/\r$/, "") });
    }
    if (t.ended) {
      out.newLine(0);
      out.cur.tokens.push({ type: "text", value: "\\.", cls: "p" });
    }
    return;
  }
  out.newLine(0);
  const m = /^(\S+)(.*)$/.exec(t.value) || [t.value, t.value, ""];
  out.cur.tokens.push({ type: "text", value: t.type === "go" ? m[1].toUpperCase() : m[1], cls: "kw" });
  if (m[2]) out.cur.tokens.push({ type: "text", value: m[2] });
}

// ---------------------------------------------------------------------------
// Statements

const PROC_START = words("BEGIN IF WHILE LOOP REPEAT FOR CASE");

function procStartsAt(toks, i) {
  const t = toks[i];
  if (!isW(t)) return t?.type === "op" && t.value === "<<";
  if (t.upper === "BEGIN") return isBlockBegin(toks, i);
  if (t.upper === "FOR") {
    const n = nextCode(toks, i);
    return !(isW(n) && ["UPDATE", "SHARE", "NO", "KEY", "XML", "JSON"].includes(n.upper));
  }
  if (PROC_START.has(t.upper)) return true;
  // MySQL labels: `name: LOOP`.
  const n = nextCode(toks, i);
  if (n && n.type === "op" && n.value === ":") {
    const nn = nextCode(toks, toks.indexOf(n));
    return isW(nn) && ["BEGIN", "LOOP", "WHILE", "REPEAT", "FOR"].includes(nn.upper);
  }
  return false;
}

function emitStatement(out, toks, indent, opts) {
  const code = toks.filter((t) => t.type !== "comment");
  if (!code.length) {
    for (const c of toks) {
      out.newLine(indent);
      out.pushComment(c);
    }
    return;
  }
  const startAt = toks.indexOf(code[0]);
  if (procStartsAt(toks, startAt)) {
    emitProc(out, toks, indent, opts);
    return;
  }
  const kind = opts.kind || statementKind(toks);
  if (kind === "ddl" && (code[0].upper === "CREATE" || code[0].upper === "ALTER")) {
    const b = toks.findIndex((t, k) => isW(t, "BEGIN") && isBlockBegin(toks, k));
    if (b > 0) {
      const head = toks.slice(0, b);
      classify(head, "ddl");
      emitHead(out, nest(head), indent);
      emitProc(out, toks.slice(b), indent, opts);
      return;
    }
  }
  classify(toks, kind);
  const items = nest(toks);
  if (kind === "dml") formatSequence(out, items, indent, "dml");
  else formatOther(out, items, indent, code[0].upper);
}

function formatOther(out, items, indent, first) {
  let split = -1;
  if (first !== "GRANT" && first !== "REVOKE") {
    for (let i = 1; i < items.length; i += 1) {
      const it = items[i];
      if (!isKw(it)) continue;
      const prev = items[i - 1];
      const start = it.upper === "SELECT" || it.upper === "VALUES" || (it.upper === "WITH" && isCteStart(items, i));
      if (!start) continue;
      if (isKw(prev) && (prev.upper === "ON" || prev.upper === "GRANT" || prev.upper === "REVOKE")) continue;
      if (isKw(prev, "FOR") && !isKw(items[i - 2], "CURSOR")) continue;
      if (prev && !prev.kind && prev.type === "punct" && prev.value === ",") continue;
      split = i;
      break;
    }
  }
  const head = split < 0 ? items : items.slice(0, split);
  emitHead(out, head, indent);
  if (split >= 0) formatSequence(out, items.slice(split), indent, "dml");
}

function emitHead(out, head, indent) {
  const ups = head.map((it) => (isKw(it) ? it.upper : ""));
  const isFn = ups[0] === "CREATE" && ups.some((u, k) => (u === "FUNCTION" || u === "PROCEDURE") && k < 6);
  const isTrigger = ups[0] === "CREATE" && ups.some((u, k) => u === "TRIGGER" && k < 6);
  const breaks = new Set();
  if (isFn) {
    const words = ["RETURNS", "LANGUAGE", "IMMUTABLE", "STABLE", "VOLATILE", "STRICT", "SECURITY", "PARALLEL", "COST", "AS"];
    head.forEach((it, k) => {
      if (k > 0 && isKw(it) && words.includes(it.upper) && !(it.upper === "STRICT" && isKw(head[k - 1]))) breaks.add(k);
    });
  } else if (isTrigger) {
    const words = ["BEFORE", "AFTER", "INSTEAD", "FOR", "WHEN", "EXECUTE", "REFERENCING"];
    head.forEach((it, k) => {
      if (k > 2 && isKw(it) && words.includes(it.upper)) breaks.add(k);
    });
  } else if (ups[0] === "CREATE" && ups.some((u, k) => u === "INDEX" && k < 4)) {
    head.forEach((it, k) => {
      if (k > 2 && isKw(it, "WHERE")) breaks.add(k);
    });
  } else if (ups[0] === "ALTER" && ups[1] === "TABLE") {
    const commas = head.filter((it) => !it.kind && it.type === "punct" && it.value === ",").length;
    if (commas > 0) {
      let k = 2;
      while (isKw(head[k]) && ["ONLY", "IF", "EXISTS"].includes(head[k].upper)) k += 1;
      k += 1;
      while (head[k] && !head[k].kind && head[k].type === "punct" && head[k].value === ".") k += 2;
      out.newLine(indent);
      emitItems(out, head.slice(0, k));
      out.openBlock();
      emitList(out, splitComma(head.slice(k)), indent + INDENT);
      out.closeBlock();
      return;
    }
  }
  let seg = [];
  const flush = () => {
    if (!seg.length) return;
    out.newLine(indent);
    emitItems(out, seg);
    seg = [];
  };
  head.forEach((it, k) => {
    if (breaks.has(k)) flush();
    seg.push(it);
  });
  flush();
}

// ---------------------------------------------------------------------------
// Clauses

function kwAt(items, i, up) {
  return isKw(items[i], up);
}

function isCteStart(items, i) {
  let j = i + 1;
  if (kwAt(items, j, "RECURSIVE")) j += 1;
  const name = items[j];
  if (!name || name.kind || (name.type !== "word" && name.type !== "qname")) return false;
  j += 1;
  if (isGroup(items[j])) j += 1;
  return kwAt(items, j, "AS");
}

function clauseAt(items, i, mode, ctx) {
  const t = items[i];
  if (!isKw(t)) return null;
  const up = t.upper;
  const at = (k, w) => kwAt(items, i + k, w);
  const prev = items[i - 1];

  if (mode === "window") {
    if ((up === "PARTITION" || up === "ORDER") && at(1, "BY")) return { len: 2, kind: "list" };
    if (up === "ROWS" || up === "RANGE" || up === "GROUPS") return { len: 1, kind: "plain" };
    return null;
  }

  switch (up) {
    case "SELECT": {
      let len = 1;
      if (at(len, "DISTINCT") || at(len, "ALL")) {
        len += 1;
        if (at(len - 1, "DISTINCT") && at(len, "ON") && isGroup(items[i + len + 1])) len += 2;
      }
      if (at(len, "TOP")) {
        len += 1;
        if (items[i + len] && (isGroup(items[i + len]) || items[i + len].type === "number" || items[i + len].type === "param")) len += 1;
        if (at(len, "PERCENT")) len += 1;
        if (at(len, "WITH") && at(len + 1, "TIES")) len += 2;
      }
      if (at(len, "AS") && (at(len + 1, "STRUCT") || at(len + 1, "VALUE"))) len += 2;
      return { len, kind: "list" };
    }
    case "FROM":
      if (isKw(prev, "DISTINCT")) return null;
      return { len: 1, kind: "list" };
    case "WHERE":
    case "HAVING":
    case "QUALIFY":
      return { len: 1, kind: "cond" };
    case "GROUP":
      if (!at(1, "BY")) return null;
      return { len: at(2, "ALL") || at(2, "DISTINCT") ? 3 : 2, kind: "list" };
    case "ORDER":
    case "PARTITION":
    case "CLUSTER":
    case "DISTRIBUTE":
    case "SORT":
      return at(1, "BY") ? { len: 2, kind: "list" } : null;
    case "LIMIT":
    case "OFFSET":
    case "FETCH":
      return { len: 1, kind: "plain" };
    case "UNION":
    case "INTERSECT":
    case "EXCEPT":
    case "MINUS":
      return { len: at(1, "ALL") || at(1, "DISTINCT") ? 2 : 1, kind: "setop" };
    case "WINDOW":
      return { len: 1, kind: "list" };
    case "WITH":
      return isCteStart(items, i) ? { len: at(1, "RECURSIVE") ? 2 : 1, kind: "with" } : null;
    case "INSERT":
    case "REPLACE": {
      let len = 1;
      if (at(len, "OR") && items[i + len + 1]) len += 2;
      if (at(len, "IGNORE") || at(len, "LOW_PRIORITY") || at(len, "DELAYED")) len += 1;
      if (at(len, "INTO")) len += 1;
      else if (at(len, "OVERWRITE")) len += at(len + 1, "TABLE") ? 2 : 1;
      if (up === "REPLACE" && len === 1) return null;
      return { len, kind: "plain" };
    }
    case "VALUES":
      if (isKw(prev, "DEFAULT")) return null;
      return { len: 1, kind: "list" };
    case "UPDATE":
      return { len: 1, kind: "plain" };
    case "SET":
      return { len: 1, kind: "list" };
    case "DELETE":
      return { len: at(1, "FROM") ? 2 : 1, kind: "plain" };
    case "RETURNING":
    case "OUTPUT":
      return { len: 1, kind: "list" };
    case "INTO":
      return { len: 1, kind: "plain" };
    case "MERGE":
      return { len: at(1, "INTO") ? 2 : 1, kind: "plain" };
    case "USING":
      return ctx.merge || ctx.first === "DELETE" ? { len: 1, kind: "plain" } : null;
    case "ON":
      if (at(1, "CONFLICT")) return { len: 2, kind: "plain" };
      if (at(1, "DUPLICATE") && at(2, "KEY") && at(3, "UPDATE")) return { len: 4, kind: "list" };
      if (ctx.merge && !ctx.joined) return { len: 1, kind: "cond" };
      return null;
    case "DO":
      if (at(1, "UPDATE") && at(2, "SET")) return { len: 3, kind: "list" };
      if (at(1, "NOTHING")) return { len: 2, kind: "setop" };
      return null;
    case "WHEN": {
      if (!ctx.merge) return null;
      let k = 1;
      while (items[i + k] && !kwAt(items, i + k, "THEN")) k += 1;
      return { len: k + 1, kind: "nested" };
    }
    case "FOR": {
      const n = items[i + 1];
      if (!isKw(n) || !["UPDATE", "SHARE", "NO", "KEY", "XML", "JSON", "BROWSE"].includes(n.upper)) return null;
      let len = 2;
      if (n.upper === "NO") len = 4;
      else if (n.upper === "KEY") len = 3;
      return { len, kind: "plain" };
    }
    case "CONNECT":
      return at(1, "BY") ? { len: 2, kind: "cond" } : null;
    case "START":
      return at(1, "WITH") ? { len: 2, kind: "cond" } : null;
    case "LEFT":
    case "RIGHT":
    case "FULL":
    case "INNER":
    case "CROSS":
    case "NATURAL":
    case "JOIN":
    case "STRAIGHT_JOIN":
    case "OUTER": {
      let k = 0;
      if (at(k, "NATURAL")) k += 1;
      if (at(k, "LEFT") || at(k, "RIGHT") || at(k, "FULL")) {
        k += 1;
        if (at(k, "OUTER") || at(k, "SEMI") || at(k, "ANTI")) k += 1;
      } else if (at(k, "INNER") || at(k, "CROSS")) k += 1;
      if (at(k, "JOIN") || at(k, "STRAIGHT_JOIN")) return { len: k + 1, kind: "join" };
      if ((at(0, "CROSS") || at(0, "OUTER")) && at(1, "APPLY")) return { len: 2, kind: "join" };
      return null;
    }
    default:
      return null;
  }
}

function splitClauses(items, mode) {
  const f = firstCode(items);
  const ctx = { first: isKw(f) ? f.upper : "", merge: isKw(f, "MERGE"), joined: false };
  const segs = [];
  let cur = { kind: "lead", head: [], body: [], lead: [] };
  for (let i = 0; i < items.length; ) {
    const m = clauseAt(items, i, mode, ctx);
    if (m) {
      const lead = [];
      while (cur.body.length && isComment(cur.body[cur.body.length - 1]) && cur.body[cur.body.length - 1].nl > 0) {
        lead.unshift(cur.body.pop());
      }
      if (cur.kind !== "lead" || cur.body.length || cur.lead.length) segs.push(cur);
      cur = { kind: m.kind, head: items.slice(i, i + m.len), body: [], lead };
      if (m.kind === "join") ctx.joined = true;
      i += m.len;
      if (m.kind === "nested") {
        while (i < items.length && !(isKw(items[i], "WHEN") && clauseAt(items, i, mode, ctx))) cur.body.push(items[i++]);
      }
      continue;
    }
    cur.body.push(items[i]);
    i += 1;
  }
  if (cur.kind !== "lead" || cur.body.length || cur.lead.length) segs.push(cur);
  return segs;
}

function formatSequence(out, items, indent, mode) {
  for (const seg of splitClauses(items, mode)) emitClause(out, seg, indent, mode);
}

function emitClause(out, seg, indent, mode) {
  for (const c of seg.lead) {
    out.newLine(indent);
    out.pushComment(c);
  }
  if (seg.kind === "lead") {
    emitLine(out, seg.body, indent);
    return;
  }
  if (seg.kind === "with") {
    emitWith(out, seg, indent);
    return;
  }
  if (seg.kind === "setop") {
    out.newLine(indent);
    emitItems(out, seg.head);
    emitLine(out, seg.body, indent);
    return;
  }
  out.newLine(indent);
  emitItems(out, seg.head);
  const body = seg.body.slice();
  while (body.length && isComment(body[0]) && body[0].nl === 0) out.pushComment(body.shift());
  if (!body.some((it) => !isComment(it))) {
    for (const c of body) out.pushComment(c);
    return;
  }
  out.openBlock();
  const inner = indent + INDENT;
  if (seg.kind === "list") emitList(out, splitComma(body), inner);
  else if (seg.kind === "cond") emitCond(out, body, inner);
  else if (seg.kind === "join") emitJoin(out, body, inner);
  else if (seg.kind === "nested") formatSequence(out, body, inner, mode);
  else emitLine(out, body, inner);
  out.closeBlock();
}

function emitWith(out, seg, indent) {
  const chunks = splitComma(seg.body);
  chunks.forEach((ch, k) => {
    for (const c of ch.lead) {
      out.newLine(indent);
      out.pushComment(c);
    }
    out.newLine(indent);
    if (k === 0) emitItems(out, seg.head);
    emitItems(out, ch.items, ch.comma ? 1 : 0);
    if (ch.comma) out.pushPunct(ch.comma);
    for (const c of ch.trail) out.pushComment(c);
  });
  if (!chunks.length) {
    out.newLine(indent);
    emitItems(out, seg.head);
  }
}

function emitJoin(out, body, indent) {
  const at = body.findIndex((it) => isKw(it, "ON") || isKw(it, "USING"));
  const table = at < 0 ? body : body.slice(0, at);
  if (table.length) emitLine(out, table, indent);
  if (at < 0) return;
  for (const part of splitBool(body.slice(at))) emitLine(out, part, indent);
}

function emitLine(out, items, indent) {
  if (!items.length) return;
  out.newLine(indent);
  emitItems(out, items);
}

function splitComma(items) {
  const chunks = [];
  let cur = { lead: [], items: [], comma: null, trail: [] };
  for (const it of items) {
    if (!it.kind && it.type === "punct" && it.value === ",") {
      cur.comma = it;
      chunks.push(cur);
      cur = { lead: [], items: [], comma: null, trail: [] };
      continue;
    }
    if (isComment(it) && !cur.items.length) {
      if (it.nl === 0 && chunks.length && !cur.lead.length) {
        chunks[chunks.length - 1].trail.push(it);
        continue;
      }
      cur.lead.push(it);
      continue;
    }
    cur.items.push(it);
  }
  if (cur.items.length || cur.lead.length) chunks.push(cur);
  for (const ch of chunks) {
    if (!ch.comma) continue;
    while (ch.items.length > 1 && isComment(ch.items[ch.items.length - 1])) ch.trail.unshift(ch.items.pop());
  }
  return chunks;
}

function splitBool(items) {
  const parts = [[]];
  let between = 0;
  for (const it of items) {
    if (isKw(it, "BETWEEN")) between += 1;
    if (isKw(it, "AND") && between > 0) {
      between -= 1;
      parts[parts.length - 1].push(it);
      continue;
    }
    if ((isKw(it, "AND") || isKw(it, "OR")) && parts[parts.length - 1].some((x) => !isComment(x))) {
      parts.push([it]);
      continue;
    }
    parts[parts.length - 1].push(it);
  }
  return parts.filter((p) => p.length);
}

function hasBool(items) {
  return splitBool(items).length > 1;
}

function emitList(out, chunks, indent) {
  if (chunks.length > 3 && chunks.every((ch) => isLiteralChunk(ch))) {
    emitFill(out, chunks, indent);
    return;
  }
  for (const ch of chunks) {
    for (const c of ch.lead) {
      out.newLine(indent);
      out.pushComment(c);
    }
    if (!ch.items.length) continue;
    out.newLine(indent);
    emitItems(out, ch.items, ch.comma ? 1 : 0);
    if (ch.comma) out.pushPunct(ch.comma);
    for (const c of ch.trail) out.pushComment(c);
  }
}

function isLiteralChunk(ch) {
  if (ch.lead.length || ch.trail.length) return false;
  const code = ch.items;
  if (code.length === 1) {
    if (isKw(code[0], "NULL")) return true;
    return ["number", "string", "param"].includes(code[0].type) && !code[0].kind && tokLen(code[0]) < 40;
  }
  return code.length === 2 && code[0].type === "op" && code[0].unary && code[1].type === "number";
}

function emitFill(out, chunks, indent) {
  out.newLine(indent);
  for (const ch of chunks) {
    const w = seqWidth(ch.items) + (ch.comma ? 1 : 0);
    if (out.prev && out.col + 1 + w > WIDTH) out.newLine(indent);
    emitItems(out, ch.items, ch.comma ? 1 : 0);
    if (ch.comma) out.pushPunct(ch.comma);
  }
}

function emitCond(out, items, indent) {
  for (const part of splitBool(items)) emitLine(out, part, indent);
}

function restWidth(items, k, extra) {
  let w = 0;
  let prev = null;
  for (let j = k + 1; j < items.length; j += 1) {
    const it = items[j];
    const first = firstTok(it);
    if (prev && spaceBetween(prev, first)) w += 1;
    if (it.kind) return w + tokLen(it.open);
    w += tokLen(it);
    prev = it;
  }
  return w + extra;
}

function emitItems(out, items, extra = 0) {
  for (let k = 0; k < items.length; k += 1) {
    const it = items[k];
    if (isGroup(it)) emitGroup(out, it, items, k, extra);
    else if (isCase(it)) emitCase(out, it, items, k, extra);
    else if (it.type === "comment") out.pushComment(it);
    else if (it.type === "string" && it.body) emitBody(out, it);
    else if (it.type === "punct" && (it.value === "," || it.value === ";")) out.pushPunct(it);
    else out.push(it);
  }
}

function fits(out, it, items, k, extra) {
  const space = out.prev && spaceBetween(out.prev, firstTok(it)) ? 1 : 0;
  return out.col + space + itemWidth(it) + restWidth(items, k, extra) <= WIDTH;
}

function emitGroup(out, g, items, k, extra) {
  const breakable = g.items.some((x) => !isComment(x)) || g.items.length;
  const must = g.forceBreak || isQuery(g.items) || hasLineComment(g) || hasBody(g);
  if (!breakable || (!must && fits(out, g, items, k, extra))) {
    out.push(g.open);
    emitItems(out, g.items);
    if (g.close) out.push(g.close);
    else out.truncated = true;
    return;
  }
  out.push(g.open);
  const base = out.lineIndent;
  const inner = g.items.slice();
  while (inner.length && isComment(inner[0]) && inner[0].nl === 0) out.pushComment(inner.shift());
  out.openBlock();
  const at = base + INDENT;
  if (isQuery(inner)) formatSequence(out, inner, at, "dml");
  else if (isWindowSpec(inner)) formatSequence(out, inner, at, "window");
  else {
    const chunks = splitComma(inner);
    if (chunks.length > 1) emitList(out, chunks, at);
    else if (hasBool(inner)) emitCond(out, inner, at);
    else if (chunks.length === 1) {
      for (const c of chunks[0].lead) {
        out.newLine(at);
        out.pushComment(c);
      }
      emitLine(out, chunks[0].items, at);
    }
  }
  out.closeBlock();
  if (g.close) {
    out.newLine(base);
    out.push(g.close);
  } else out.truncated = true;
}

function emitCase(out, c, items, k, extra) {
  const arms = [];
  const base = [];
  for (const it of c.items) {
    if (isKw(it, "WHEN") || isKw(it, "ELSE")) arms.push([it]);
    else if (arms.length) arms[arms.length - 1].push(it);
    else base.push(it);
  }
  const whens = arms.filter((a) => isKw(a[0], "WHEN")).length;
  if (whens < 2 && !hasLineComment(c) && fits(out, c, items, k, extra)) {
    out.push(c.open);
    emitItems(out, c.items);
    if (c.close) out.push(c.close);
    else out.truncated = true;
    return;
  }
  out.push(c.open);
  emitItems(out, base);
  const indent = out.lineIndent;
  out.openBlock();
  for (const arm of arms) emitLine(out, arm, indent + INDENT);
  out.closeBlock();
  if (c.close) {
    out.newLine(indent);
    out.push(c.close);
  } else out.truncated = true;
}

// ---------------------------------------------------------------------------
// Function bodies

const SQL_LANGS = new Set(["sql", "plpgsql", "plsql", "tsql", "plpgsql_check"]);

function emitBody(out, t) {
  const quote = { type: "op", value: t.quote, cls: "qt" };
  out.push(quote);
  const base = out.lineIndent;
  const indent = base + INDENT;
  const body = t.value.replace(/^\s*\n/, "").replace(/\s+$/, "");
  let nodes = null;
  if (SQL_LANGS.has(t.lang)) {
    try {
      const lexer = new Lexer(body);
      const toks = lexer.run();
      if (!lexer.truncated) {
        const sub = new Out();
        emitProc(sub, toks, indent, { section: true });
        nodes = sub.root;
      }
    } catch {
      nodes = null;
    }
  }
  if (!nodes) nodes = verbatimBody(body, indent, SQL_LANGS.has(t.lang));
  out.openBlock();
  out.appendNodes(nodes);
  out.closeBlock();
  out.newLine(base);
  if (t.closed !== false) out.push(quote);
  else out.truncated = true;
}

function verbatimBody(body, indent, highlight) {
  const lines = body.split("\n").map((l) => l.replace(/\r$/, ""));
  const strip = Math.min(...lines.filter((l) => l.trim()).map((l) => /^[ \t]*/.exec(l)[0].length));
  const cut = Number.isFinite(strip) ? strip : 0;
  const text = lines.map((l) => l.slice(Math.min(cut, /^[ \t]*/.exec(l)[0].length))).join("\n");
  const nodes = highlight ? verbatimNodes(text) : text.split("\n").map((l) => ({ type: "line", tokens: [{ type: "text", value: l }] }));
  for (const n of nodes) {
    if (n.tokens.length) n.tokens.unshift({ type: "space", value: " ".repeat(indent) });
  }
  return nodes;
}

// ---------------------------------------------------------------------------
// Procedural blocks (BEGIN … END, IF … END IF, loops)

function emitProc(out, toks, indent, opts) {
  const p = { toks, i: 0 };
  procList(out, p, indent, new Set(), opts);
}

function peekCode(p) {
  for (let j = p.i; j < p.toks.length; j += 1) {
    if (p.toks[j].type !== "comment") return p.toks[j];
  }
  return null;
}

function upAt(p) {
  const t = p.toks[p.i];
  return isW(t) ? t.upper : "";
}

function procList(out, p, indent, stops, opts) {
  let count = 0;
  while (p.i < p.toks.length) {
    const t = p.toks[p.i];
    if (t.type === "comment") {
      if (t.nl === 0 && out.cur && count) out.pushComment(t);
      else {
        if (count && t.nl >= 2) out.blank();
        out.newLine(indent);
        out.pushComment(t);
      }
      p.i += 1;
      continue;
    }
    if (isTerm(t)) {
      if (out.cur && count) out.pushPunct({ type: "punct", value: t.value, cls: "p" });
      p.i += 1;
      continue;
    }
    if (stops.has(upAt(p))) return;
    if (count && t.nl >= 2) out.blank();
    procStatement(out, p, indent, stops, opts);
    count += 1;
  }
}

// Collect tokens until `pred` matches at depth 0; the matching token is not consumed.
function takeUntil(p, pred) {
  const start = p.i;
  let depth = 0;
  let cases = 0;
  while (p.i < p.toks.length) {
    const t = p.toks[p.i];
    if (t.type === "punct" && (t.value === "(" || t.value === "[")) depth += 1;
    else if (t.type === "punct" && (t.value === ")" || t.value === "]")) depth = Math.max(0, depth - 1);
    else if (depth === 0 && cases === 0 && p.i > start && pred(t, p.i)) break;
    else if (isW(t, "CASE") && p.i > start) cases += 1;
    else if (isW(t, "END") && cases > 0) cases -= 1;
    else if (depth === 0 && cases === 0 && isTerm(t)) break;
    p.i += 1;
  }
  return p.toks.slice(start, p.i);
}

function emitPiece(out, toks, indent, kind = "other") {
  classify(toks, kind);
  out.newLine(indent);
  emitItems(out, nest(toks));
}

function takeTerm(out, p) {
  const t = p.toks[p.i];
  if (isTerm(t)) {
    out.pushPunct({ type: t.type, value: t.value, cls: "p" });
    p.i += 1;
  }
}

function procStatement(out, p, indent, stops, opts) {
  const toks = p.toks;
  const t = toks[p.i];

  if (t.type === "op" && t.value === "<<") {
    const piece = takeUntil(p, (x) => x.type === "op" && x.value === ">>");
    if (p.toks[p.i]?.value === ">>") piece.push(toks[p.i++]);
    emitPiece(out, piece, indent);
    return;
  }

  let label = [];
  const n1 = nextCode(toks, p.i);
  if (isW(t) && n1 && n1.type === "op" && n1.value === ":" && !PROC_START.has(t.upper)) {
    const j = toks.indexOf(n1);
    const nn = nextCode(toks, j);
    if (isW(nn) && ["BEGIN", "LOOP", "WHILE", "REPEAT", "FOR"].includes(nn.upper)) {
      label = toks.slice(p.i, j + 1);
      p.i = toks.indexOf(nn);
    }
  }

  const up = upAt(p);
  if (up === "BEGIN" && isBlockBegin(toks, p.i)) {
    const head = [...label, toks[p.i++]];
    if (["TRY", "CATCH", "ATOMIC"].includes(upAt(p))) head.push(toks[p.i++]);
    else if (upAt(p) === "NOT" && isW(nextCode(toks, p.i), "ATOMIC")) head.push(toks[p.i++], toks[p.i++]);
    emitPiece(out, head, indent);
    out.openBlock();
    procList(out, p, indent + INDENT, new Set(["END", "EXCEPTION"]), { ...opts, section: false });
    out.closeBlock();
    if (upAt(p) === "EXCEPTION") {
      emitPiece(out, [toks[p.i++]], indent);
      out.openBlock();
      procArms(out, p, indent + INDENT, opts);
      out.closeBlock();
    }
    emitEnd(out, p, indent);
    return;
  }

  if (up === "DECLARE" && opts.section) {
    emitPiece(out, [toks[p.i++]], indent);
    out.openBlock();
    while (p.i < toks.length) {
      const c = toks[p.i];
      if (c.type === "comment") {
        out.newLine(indent + INDENT);
        out.pushComment(c);
        p.i += 1;
        continue;
      }
      if (isW(c, "BEGIN")) break;
      const stmt = takeUntil(p, () => false);
      emitStatement(out, stmt, indent + INDENT, { kind: "decl" });
      takeTerm(out, p);
    }
    out.closeBlock();
    return;
  }

  if (up === "IF") {
    const save = p.i;
    const head = takeUntil(p, (x) => isW(x, "THEN"));
    if (isW(toks[p.i], "THEN")) {
      head.push(toks[p.i++]);
      emitPiece(out, [...label, ...head], indent);
      out.openBlock();
      procList(out, p, indent + INDENT, new Set(["ELSIF", "ELSEIF", "ELSE", "END"]), opts);
      out.closeBlock();
      while (p.i < toks.length) {
        const w = upAt(p);
        if (w === "ELSIF" || w === "ELSEIF") {
          const h = takeUntil(p, (x) => isW(x, "THEN"));
          if (isW(toks[p.i], "THEN")) h.push(toks[p.i++]);
          emitPiece(out, h, indent);
        } else if (w === "ELSE") {
          emitPiece(out, [toks[p.i++]], indent);
        } else break;
        out.openBlock();
        procList(out, p, indent + INDENT, new Set(["ELSIF", "ELSEIF", "ELSE", "END"]), opts);
        out.closeBlock();
      }
      emitEnd(out, p, indent);
      return;
    }
    p.i = save;
    procTsql(out, p, indent, stops, opts, label);
    return;
  }

  if (up === "WHILE" || up === "FOR" || up === "LOOP") {
    const save = p.i;
    const head = up === "LOOP" ? [toks[p.i++]] : takeUntil(p, (x) => isW(x, "LOOP") || isW(x, "DO"));
    if (up !== "LOOP" && (isW(toks[p.i], "LOOP") || isW(toks[p.i], "DO"))) head.push(toks[p.i++]);
    else if (up !== "LOOP") {
      p.i = save;
      procTsql(out, p, indent, stops, opts, label);
      return;
    }
    emitPiece(out, [...label, ...head], indent);
    out.openBlock();
    procList(out, p, indent + INDENT, new Set(["END"]), opts);
    out.closeBlock();
    emitEnd(out, p, indent);
    return;
  }

  if (up === "REPEAT") {
    emitPiece(out, [...label, toks[p.i++]], indent);
    out.openBlock();
    procList(out, p, indent + INDENT, new Set(["UNTIL", "END"]), opts);
    out.closeBlock();
    if (upAt(p) === "UNTIL") emitPiece(out, takeUntil(p, (x) => isW(x, "END")), indent);
    emitEnd(out, p, indent);
    return;
  }

  if (up === "CASE") {
    const head = takeUntil(p, (x) => isW(x, "WHEN"));
    emitPiece(out, head, indent);
    out.openBlock();
    procArms(out, p, indent + INDENT, opts);
    out.closeBlock();
    emitEnd(out, p, indent);
    return;
  }

  const stmt = takeUntil(p, (x) => isW(x) && stops.has(x.upper));
  const trail = [];
  while (stmt.length > 1 && stmt[stmt.length - 1].type === "comment") trail.unshift(stmt.pop());
  emitStatement(out, [...label, ...stmt], indent, { section: false });
  takeTerm(out, p);
  for (const c of trail) out.pushComment(c);
}

// T-SQL style `IF cond stmt [ELSE stmt]` / `WHILE cond stmt` without THEN or LOOP.
function procTsql(out, p, indent, stops, opts, label) {
  const toks = p.toks;
  const first = toks[p.i];
  const head = takeUntil(p, (x, k) => isW(x) && TSQL_STMT.has(x.upper) && x !== first && !isW(toks[k - 1], "NOT"));
  emitPiece(out, [...label, ...head], indent);
  if (p.i >= toks.length || isTerm(toks[p.i])) {
    takeTerm(out, p);
    return;
  }
  out.openBlock();
  procStatement(out, p, indent + INDENT, new Set([...stops, "ELSE"]), opts);
  out.closeBlock();
  const save = p.i;
  while (p.i < toks.length && toks[p.i].type === "comment") p.i += 1;
  if (isW(first, "IF") && upAt(p) === "ELSE") {
    emitPiece(out, [toks[p.i++]], indent);
    out.openBlock();
    procStatement(out, p, indent + INDENT, stops, opts);
    out.closeBlock();
  } else p.i = save;
}

function procArms(out, p, indent, opts) {
  const toks = p.toks;
  while (p.i < toks.length) {
    const w = upAt(p);
    if (toks[p.i].type === "comment") {
      out.newLine(indent);
      out.pushComment(toks[p.i++]);
      continue;
    }
    if (w === "WHEN") {
      const head = takeUntil(p, (x) => isW(x, "THEN"));
      if (isW(toks[p.i], "THEN")) head.push(toks[p.i++]);
      emitPiece(out, head, indent);
    } else if (w === "ELSE") {
      emitPiece(out, [toks[p.i++]], indent);
    } else return;
    out.openBlock();
    procList(out, p, indent + INDENT, new Set(["WHEN", "ELSE", "END"]), opts);
    out.closeBlock();
  }
}

function emitEnd(out, p, indent) {
  const toks = p.toks;
  if (upAt(p) !== "END") {
    out.truncated = true;
    return;
  }
  const head = [toks[p.i++]];
  while (p.i < toks.length) {
    const t = toks[p.i];
    if (!isW(t) || t.nl > 0) break;
    if (END_FOLLOW.has(t.upper)) {
      head.push(t);
      p.i += 1;
      continue;
    }
    const n = toks[p.i + 1];
    if (!n || isTerm(n) || n.nl > 0) {
      head.push(t);
      p.i += 1;
    }
    break;
  }
  emitPiece(out, head, indent);
  for (const t of head.slice(1)) {
    if (!END_FOLLOW.has(t.upper)) setKind(t, "ident");
    else setKind(t, "kw");
  }
  takeTerm(out, p);
}

// ---------------------------------------------------------------------------
// Verbatim (source layout, highlighted): fallback when formatting fails

function verbatimNodes(src, tokens, stmts) {
  if (!tokens) {
    tokens = new Lexer(src).run();
    stmts = splitStatements(tokens);
  }
  for (const st of stmts) {
    if (!st.special) {
      try {
        classify(st.tokens, statementKind(st.tokens));
      } catch {
        /* keep raw */
      }
    }
  }
  const segs = [];
  let pos = 0;
  for (const t of tokens) {
    if (t.start > pos) segs.push({ text: src.slice(pos, t.start) });
    segs.push({ text: t.raw, cls: verbatimCls(t) });
    pos = t.end;
  }
  if (pos < src.length) segs.push({ text: src.slice(pos) });
  const lines = [[]];
  for (const seg of segs) {
    const parts = seg.text.split(/\r?\n/);
    parts.forEach((part, k) => {
      if (k > 0) lines.push([]);
      if (part) lines[lines.length - 1].push({ type: "text", value: part.replace(/\r$/, ""), cls: seg.cls });
    });
  }
  while (lines.length > 1 && !lines[lines.length - 1].length) lines.pop();
  return lines.map((tokens) => ({ type: "line", tokens }));
}

function verbatimCls(t) {
  switch (t.type) {
    case "comment":
      return t.tpl ? "param" : "c";
    case "string":
      return "s";
    case "meta":
    case "go":
      return "kw";
    case "copydata":
    case "qname":
      return undefined;
    default:
      return t.cls;
  }
}
